name: CI

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PHP Mess Detector
        run: ./vendor/bin/phpmd src text ./phpmd.xml

      - name: PHP Code Sniffer
        run: ./vendor/bin/phpcs --standard=phpcs.xml

      - name: PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --verbose --stop-on-violation

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit-ci.xml
